
import store from '../store'


const locales={
  'ru-Ru': {
    'exit': 'Выход',
    'profile': 'Профиль',
    'update_name_profile': 'Изменить имя профиля',
    'update': 'Обновить',
    'score': 'Счёт',
    'home_score': 'Валютные счета',
    'course_currency': 'Курс валют',
    'currency': 'Валюта',
    'can_buy': 'Продажа',
    'can_seil': 'Покупка',
    'date': 'Дата',
    'history': 'История',
    'amount': 'Сумма',
    'category': 'Категория',
    'type': 'Тип',
    'open': 'Открыть',
    'Доход': 'Доход',
    'Расход': 'Расход',
    'Description': 'Описание',
    'deletex': 'Удалить',
    'message_delete': 'Вы уверенны что хотите удалить эту запись?',
    'cansel': 'Отмена',
    'planning_bad': 'Для того чтобы создать запись нужно выбрать категорию, их пока нет. Содайте её',
    'here': 'тут',
    'planning': 'Планирование',
    'balance': 'Текущий баланс',
    'spent': 'Потрачено',
    'of': 'из',
    'record': 'Записи',
    'bad_record': 'Для того чтобы создать запись нужно выбрать категорию, их пока нет. Содайте её',
    'record_ented_select_category': 'Выбор нужой категории',
    'add': 'Добавить',
    'Поле не может быть пустым': 'Поле не может быть пустым',
    'Не должно быть меньше чем 1': 'Не должно быть меньше чем 1',
    'create_category': 'Создать категорию',
    'Введите название категории': 'Введите название категории',
    'Лимит на данную категорию': 'Лимит на данную категорию',
    'Создать категорию': 'Создать категорию',
    'Редактировать категорию': 'Редактировать категорию',
    'Выберите категорию для редактирования': 'Выберите категорию для редактирования',
    'Новое название для категории': 'Новое название для категории',
    'Новый лимит категории' : 'Новый лимит категории',
    'Удаление категории и всех связанных с ней записей': 'Удаление категории и всех связанных с ней записей',
    'categories': 'Категории',
    'one_page': 'Страница детализации',
  },
  'en-Us': {
    'one_page': 'Detail page',
    'categories': 'Categories',
    'exit': 'Exit',
    'удаление категории и всех связанных с ней записей': 'Deleting a category and all related entries',
    'Новый лимит категории': 'New category limit',
    'Новое название для категории': 'Ented new category name',
    'Выберите категорию для редактирования': 'Select category from edit',
    'Редактировать категорию': 'Edit category',
    'Создать категорию': 'Create new category',
    'Лимит на данную категорию': 'Limit on this category',
    'Введите название категории': 'Ented category name',
    'create_category': 'Create new category',
    'Не должно быть меньше чем 1': 'Must not be less than 1',
    'Поле не может быть пустым': 'this field must be required',
    'add': 'Add',
    'record_ented_select_category': 'Choosing the right category',
    'bad_record': 'In order to create a record you need to attach it to a category, and you do not have a single category.',
    'record': 'Record',
    'of': 'of',
    'spent': 'Spent',
    'balance': 'Current balance',
    'planning': 'Planning',
    'here': 'here',
    'planning_bad': 'In order to create a record you need to attach it to a category, and you do not have a single category.',
    'cansel': 'Cansel',
    'message_delete': 'Are you sure you want to delete this item?',
    'deletex': 'Delete',
    'profile': 'Profile',
    'update_name_profile': 'ented update name',
    'update': 'update',
    'score': 'Score',
    'home_score': 'Accounts (in terms of currencies)',
    'course_currency': 'Exchange rate against the UAH',
    'currency': 'Currency',
    'can_buy': 'I can buy at',
    'can_seil': 'I can sell at',
    'date': 'Date',
    'history': 'History',
    'amount': 'Amount',
    'category': 'Category',
    'type': 'A type',
    'open': 'Open',
    'Доход': 'Income',
    'Расход': 'Outcome',
    'Description': 'Description'
  }
}

export default function localize(key) {

  const locale=store.getters.info.locale || 'ru-Ru'

  return locales[locale][key] || `[super localize error] ${key}`
};
